// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMGnqIYVIxrQcwz1m26fmnqKCPNNkVvHo',
    appId: '1:631505308537:android:d4b07a58e1c70c7b653da8',
    messagingSenderId: '631505308537',
    projectId: 'receiving-payment',
    databaseURL: 'https://receiving-payment-default-rtdb.firebaseio.com',
    storageBucket: 'receiving-payment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrn_N-ou5z41reqM8T_2diIvniFauJDEc',
    appId: '1:631505308537:ios:6e17527a98ed51ca653da8',
    messagingSenderId: '631505308537',
    projectId: 'receiving-payment',
    databaseURL: 'https://receiving-payment-default-rtdb.firebaseio.com',
    storageBucket: 'receiving-payment.appspot.com',
    androidClientId: '631505308537-bjifrc1emvhh1cqerln0ahs9ojrs9mdt.apps.googleusercontent.com',
    iosClientId: '631505308537-mpl8pn3p9oieojipedkfiu6oiqbdhhum.apps.googleusercontent.com',
    iosBundleId: 'com.GipPrecones.ePayment.ePayment',
  );
}
